name: eebg2026-hyphy
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - hyphy>=2.5
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - biopython
  - pyvolve
  - pyyaml
  - unzip

